### ISSUE TITLE
List of every action built into shortcuts and their parameters

### ISSUE THREAD

**Issue by pfgithub** [alexander-akhmetov/python-shortcuts#12]
If you want to be able to add actions more easily, @xAlien95 extracted a plist of all the actions in shortcuts 2.1.2,

https://raw.githubusercontent.com/pfgithub/shortcutslang/33a323c0d0356dd51730580a6574ab86431f10c6/src/Data/Shortcuts%202.1.2.json

It's missing some things like the blocks in if, choose from menu, repeat, and repeat with each. It also doesn't list any arguments for the Get Details of * and Filter * actions. It should make it easier to add actions, or if you want to it makes it possible to automate adding them.

**Comment by alexander-akhmetov** [comment]
Thank you!
