### ISSUE TITLE
name: str = '',         ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jishangiras** [alexander-akhmetov/python-shortcuts#2]
`File "/Library/Python/2.7/site-packages/shortcuts/shortcut.py", line 22
    name: str = '',
        ^
SyntaxError: invalid syntax`

Keep getting this.

Tried to run the example python as a script to produce the .shortcut

**Comment by alexander-akhmetov** [comment]
Hi! Which python version do you use? The library supports 3.6 and higher. 

I will add information about this to the readme file.

**Comment by jishangiras** [comment]
Ah, this for 2.7
Thanks !
