### ISSUE TITLE
Run_shortcut not working

### ISSUE THREAD

**Issue by pbassham** [alexander-akhmetov/python-shortcuts#3]
I am having a problem getting the run shortcut action to work. I have it formatted like this.

    [[action]]
    type = "run_shortcut"
    shortcut_name = "UpdateKit"
    show = "False"

I get the error:
<class 'shortcuts.exceptions.UnknownActionError'>: 
            Unknown shortcut action: "run_shortcut"

**Comment by alexander-akhmetov** [comment]
"Run shortcut" action wasn't released. I just uploaded a new version to the pypi: `0.10.0`, please install it :)
