### ISSUE TITLE
A project with a similar scope

### ISSUE THREAD

**Issue by joshfarrant** [alexander-akhmetov/python-shortcuts#6]
Hey Alexander! 👋

I've just been pointed your way by [this thread on r/shortcuts](https://old.reddit.com/r/shortcuts/comments/9xmjgp/creating_ios_12_shortcuts_with_javascript_and/e9thbhw/) and I thought I'd drop you a message. I know that an issue isn't the best place for this, but hey ho!

I've just released [Shortcuts JS](https://github.com/joshfarrant/shortcuts-js) which has a very similar scope to python-shortcuts, but is implemented in JavaScript rather than Python. As the projects have such a similar scope, there may well be things that can be learnt from one another's projects, so I thought I'd just introduce myself and point you in the direction of the repo, on the off chance there's something there you find interesting or useful.

I can already see that python-shortcuts implements some additional features that I'm hoping to add to Shortcuts JS at some point, mainly the shortcut → toml feature, which in my case would likely be shortcut -> JSON, or possibly shortcut -> JS.

Anyway, keep up the great work!

**Comment by enzyme69** [comment]
I am curious with both the JS and Python 🐍 to generate Siri Shortcuts... I am not a coder, but curious on whether the JS can generate 3D objects using Siri?

**Comment by alexander-akhmetov** [comment]
Hi Josh!

> I know that an issue isn't the best place for this, but hey ho!

A good way to contact contributors, I think 😄

> I've just released Shortcuts JS which has a very similar scope to python-shortcuts, but is implemented in JavaScript rather than Python.

Great project! 🙂 Nice to see that somebody else started doing this too, I like that now we have more programming languages to write Shortcuts.

Thanks for the message!

**Comment by alexander-akhmetov** [comment]
@enzyme69 I'm not sure if I understand your question correctly, but with `python-shortcuts ` and `shortcuts-js`, you can create shortcuts with Javascript or Python/toml. Also, as I know, from the Shortcuts app you can run different scripts with Pythonista and Scriptable (you can find them in the App Store). So then you can generate something if it's possible with Shortcuts app of these apps.

Maybe this will help you :)
